name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java: [ '8', '11', '17' ]

    runs-on: '${{ matrix.os }}'

    steps:
      - uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}

      - name: Cache gradle files
        uses: actions/cache@v2
        with:
          path: |
            $HOME/.gradle/caches
            $HOME/.gradle/wrapper
          key: ktb-${{ matrix.os }}-${{ matrix.java }}-${{ hashFiles('**/*.gradle*', '**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ktb-${{ matrix.os }}-${{ matrix.java }}-

      - name: Build
        shell: bash
        run: ./gradlew build

      - name: After Build
        shell: bash
        run: |
          ./gradlew --stop
          git reset --hard HEAD

      - name: Update Codecov
        shell: bash
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.java == '8' }}
        run: bash <(curl -s https://codecov.io/bash)
